# Generated by Django 6.1.1 on 2026-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_clean_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
